# Generated by Django 3.1.5 on 2021-06-18 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20210618_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarReleaseDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_release_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carreleasedate'),
        ),
    ]
