# Generated by Django 3.1.5 on 2021-06-18 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20210618_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='carreleasedate',
            options={'verbose_name_plural': 'Cars release dates'},
        ),
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(blank=True, choices=[('Tr', 'Truck'), ('Or', 'Off-roader'), ('Pc', 'Passenger car')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.cartype'),
        ),
    ]
