# Generated by Django 3.1.5 on 2021-06-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20210618_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.cartype'),
        ),
        migrations.AlterField(
            model_name='carreleasedate',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Off-roader', 'Off-roader'), ('Passenger car', 'Passenger car')], max_length=100),
        ),
    ]
