# Generated by Django 3.1.5 on 2021-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_auto_20210624_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreleasedate',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
