# Generated by Django 3.1.5 on 2021-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_auto_20210624_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreleasedate',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
