# Generated by Django 3.1.5 on 2021-06-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_auto_20210624_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreleasedate',
            name='date',
            field=models.DateField(verbose_name='Car release date'),
        ),
    ]
